image: maven:3.9-eclipse-temurin-21

testovani:
  script:
    - "mvn test"
  only:
    - develop

sestaveni:
  script:
    - "mvn javafx:jlink -B"
  artifacts:
    paths:
      - "target/*.zip"
  only:
    - main